[error] java.io.IOException: CreateFile() failed with error 3
[error] 	at sbt.internal.io.WinMilli$.getHandle(Milli.scala:275)
[error] 	at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:281)
[error] 	at sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:259)
[error] 	at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
[error] 	at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:352)
[error] 	at sbt.io.IO$.getModifiedTime(IO.scala:1143)
[error] 	at sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1212)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$fileUptodate$1(LibraryManagement.scala:130)
[error] 	at scala.runtime.java8.JFunction1$mcZJ$sp.apply(JFunction1$mcZJ$sp.java:12)
[error] 	at scala.Option.forall(Option.scala:247)
[error] 	at sbt.internal.LibraryManagement$.fileUptodate(LibraryManagement.scala:130)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$9(LibraryManagement.scala:75)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$9$adapted(LibraryManagement.scala:75)
[error] 	at scala.collection.Iterator.forall(Iterator.scala:941)
[error] 	at scala.collection.Iterator.forall$(Iterator.scala:939)
[error] 	at scala.collection.AbstractIterator.forall(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.forall(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.forall$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.forall(Iterable.scala:54)
[error] 	at sbt.internal.LibraryManagement$.upToDate$1(LibraryManagement.scala:75)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:98)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2381)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
